 [mcp]

 [mcp.servers.context7]
 type = "http"
 url = "https://mcp.context7.com/mcp"

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"
startup_timeout_ms = 30000

 [mcp.servers.shadcn]
 type = "stdio"
 command = "npx"
 args = ["shadcn@latest", "mcp"]

 [mcp.servers.firebase]
 type = "stdio"
 command = "npx"
 args = ["-y", "firebase-tools@latest", "experimental:mcp"]
